# Generated by Django 4.1.7 on 2023-03-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_service_deskripsi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='deskripsi',
        ),
        migrations.AddField(
            model_name='service',
            name='img',
            field=models.FilePathField(default=str, path='/static/images/icons/services/', recursive=True),
            preserve_default=False,
        ),
    ]
