# Generated by Django 4.1.7 on 2023-03-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_service_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='details',
            field=models.TextField(max_length=400),
        ),
    ]
